INFO:root:Starting the program...
INFO:root:Starting the program...
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='controller4221bare-ddsrikar-ndca8gxk.srv.ravcloud.com', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a2c0c50>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='controller4221bare-ddsrikar-ndca8gxk.srv.ravcloud.com', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1072f5c50>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='controller4221bare-ddsrikar-ndca8gxk.srv.ravcloud.com', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10bf33e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='controller4221bare-ddsrikar-ndca8gxk.srv.ravcloud.com', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1099ffdd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
INFO:root:Starting the program...
INFO:root:Starting the program...
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='controller4221bare-ddsrikar-ndca8gxk.srv.ravcloud.com', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b2c7dd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='controller4221bare-ddsrikar-ndca8gxk.srv.ravcloud.com', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104eccd90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
ERROR:root:HTTPSConnectionPool(host='dominospizza-prod.saas.appdynamics.com', port=443): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x104f0a510>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
ERROR:root:HTTPSConnectionPool(host='predixtest.saas.appdynamics.com', port=443): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x104f0a590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
ERROR:root:HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104f0a610>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO:root:Starting the program...
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='controller4221bare-ddsrikar-ndca8gxk.srv.ravcloud.com', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110ca4150>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
ERROR:root:HTTPSConnectionPool(host='dominospizza-prod.saas.appdynamics.com', port=443): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110cdc9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
ERROR:root:HTTPSConnectionPool(host='predixtest.saas.appdynamics.com', port=443): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x110cdc1d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
ERROR:root:HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110c7ea50>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b040bd0>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102b70bd0>: Failed to establish a new connection: [Errno 61] Connection refused',))
INFO:root:Starting the program...
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='controller4221bare-ddsrikar-ndca8gxk.srv.ravcloud.com', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10dda2d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
INFO:root:Starting the program...
ERROR:root:HTTPConnectionPool(host='controller4221bare-ddsrikar-ndca8gxk.srv.ravcloud.com', port=8090): Max retries exceeded with url: /controller/rest/applications?output=JSON (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102a580d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
INFO:root:Starting the program...
INFO:root:Starting the program...
